name: tvrip-test-suite

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 11
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python: "3.10"
            experimental: false
          - os: ubuntu-22.04
            python: "3.11"
            experimental: false
          - os: ubuntu-22.04
            python: "3.12"
            experimental: false

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install exuberant-ctags
          make develop

      - name: Run tests
        run: |
          make test
